const list = [
  {
    id: 1,
    title: "Curious Mind",
    author: "by Jordan Moore | 25 April 2018",
    price: 89,
    img: "https://images-na.ssl-images-amazon.com/images/I/71m+Qtq+HrL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "Its starts with us",
    author: "by Coolleen Hoover  | 1 September 2020",
    price: 98,
    img: "https://images-na.ssl-images-amazon.com/images/I/71PNGYHykrL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "The light we carry",
    author: "by Michelle Obama  | 25 November 2018",
    price: 143,
    img: "https://images-na.ssl-images-amazon.com/images/I/91MowzF+WZL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "Complete Cookbook for young chef",
    author: "by The Cook Team | 25 April 2018",
    price: 57,
    img: "https://images-na.ssl-images-amazon.com/images/I/911pI+iDkCL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "Fairy Tale",
    author: "by Stephen King  | 1 January 2018",
    price: 149,
    img: "https://images-na.ssl-images-amazon.com/images/I/81blQfKsLtL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "Life skills for teen",
    author: "by Karen Harris | 30 September 2020",
    price: 135,
    img: "https://images-na.ssl-images-amazon.com/images/I/71eA+3k5PzL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "Friends lover and Big terrible thing ",
    author: "by Methew Perry  | 1 January 2021",
    price: 693,
    img: "https://images-na.ssl-images-amazon.com/images/I/81tdvyI0MeL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "Never Finshed",
    author: "by David Goggins | 6 December 2020",
    price: 289,
    img: "https://images-na.ssl-images-amazon.com/images/I/712bDA3B6zL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "Where the CrawDad Sings",
    author: "by Delia Owens",
    price: 80,
    img: "https://images-na.ssl-images-amazon.com/images/I/81O1oy0y9eL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "Slow Horses",
    author: "by Mick Herron | 1 September 2021",
    price: 86,
    img: "https://m.media-amazon.com/images/I/51vf4bluOgL._SY291_BO1,204,203,200_QL40_FMwebp_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "Atomic Habits",
    author: "by James Clear ",
    price: 120,
    img: "https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "The Boys from Biloxi",
    author: "by John Grisham| 1 January 2015",
    price: 157,
    img: "https://images-na.ssl-images-amazon.com/images/I/71N1ryT6iGL._AC_UL210_SR195,210_.jpg",
    amount: 1,
  },
];

export default list;
